/// Exercise 2: Firebase Chat Basics (Beginner-Intermediate)
///
/// Level: Beginner-Intermediate
/// Estimated Time: 2-3 hours
///
/// Task:
/// Connect your chat UI to Firebase Firestore for real-time messaging.
/// Enable users to send and receive messages that persist in the cloud.
///
/// Requirements:
/// 1. Set up Firebase (see README.md for instructions)
/// 2. Implement user authentication (simple email/password)
/// 3. Create Firestore structure for messages
/// 4. Send messages to Firestore
/// 5. Listen to messages in real-time using Streams
/// 6. Display messages with proper timestamps
/// 7. Show sender information
///
/// Firestore Structure:
/// messages/
///   {messageId}/
///     text: string
///     senderId: string
///     senderName: string
///     timestamp: timestamp
///
/// users/
///   {userId}/
///     name: string
///     email: string
///
/// Learning Goals:
/// - Firebase initialization
/// - Firestore CRUD operations
/// - Stream builders for real-time data
/// - User authentication
/// - Timestamp handling
///
/// SETUP REQUIRED:
/// 1. Add to pubspec.yaml:
///    firebase_core: ^2.24.0
///    firebase_auth: ^4.15.0
///    cloud_firestore: ^4.13.0
///
/// 2. Run: flutterfire configure
/// 3. Follow README.md Firebase setup instructions

import 'package:flutter/material.dart';
// TODO: Import Firebase packages
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  // TODO: Ensure Flutter is initialized
  // WidgetsFlutterBinding.ensureInitialized();

  // TODO: Initialize Firebase
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Chat',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      // TODO: Use StreamBuilder to check authentication state
      // If user is logged in, show ChatScreen
      // If not logged in, show LoginScreen
      home: AuthWrapper(),
    );
  }
}

// TODO: Create AuthWrapper to handle authentication state
class AuthWrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: Use StreamBuilder with FirebaseAuth.instance.authStateChanges()
    // Return ChatScreen if user != null, else LoginScreen

    return LoginScreen(); // Temporary
  }
}

// TODO: Create LoginScreen
class LoginScreen extends StatefulWidget {
  @override
  _LoginScreenState createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  // TODO: Create TextEditingControllers for email and password

  // TODO: Create TextEditingController for name (for registration)

  bool _isLogin = true; // Toggle between login and register

  @override
  void dispose() {
    // TODO: Dispose controllers
    super.dispose();
  }

  // TODO: Implement _login method
  Future<void> _login() async {
    // Use FirebaseAuth.instance.signInWithEmailAndPassword
    // Show error if login fails
  }

  // TODO: Implement _register method
  Future<void> _register() async {
    // Use FirebaseAuth.instance.createUserWithEmailAndPassword
    // Create user document in Firestore with name
    // Show error if registration fails
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(_isLogin ? 'Login' : 'Register'),
      ),
      body: Padding(
        padding: EdgeInsets.all(16),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            // TODO: Add TextField for email

            // TODO: Add SizedBox

            // TODO: Add TextField for password

            // TODO: If registering, add TextField for name

            // TODO: Add SizedBox

            // TODO: Add ElevatedButton for login/register

            // TODO: Add TextButton to toggle between login and register
          ],
        ),
      ),
    );
  }
}

// TODO: Create ChatMessage model (same as Exercise 1)
class ChatMessage {
  final String id;
  final String text;
  final String senderId;
  final String senderName;
  final DateTime timestamp;

  ChatMessage({
    required this.id,
    required this.text,
    required this.senderId,
    required this.senderName,
    required this.timestamp,
  });

  // TODO: Create factory constructor fromFirestore
  factory ChatMessage.fromFirestore(DocumentSnapshot doc) {
    // Convert Firestore document to ChatMessage
    final data = doc.data() as Map<String, dynamic>;
    return ChatMessage(
      id: doc.id,
      text: data['text'] ?? '',
      senderId: data['senderId'] ?? '',
      senderName: data['senderName'] ?? '',
      timestamp: (data['timestamp'] as Timestamp).toDate(),
    );
  }

  // TODO: Create toMap method for saving to Firestore
  Map<String, dynamic> toMap() {
    return {
      'text': text,
      'senderId': senderId,
      'senderName': senderName,
      'timestamp': Timestamp.fromDate(timestamp),
    };
  }
}

// TODO: Create MessageBubble widget (similar to Exercise 1, but check if message is sent by current user)
class MessageBubble extends StatelessWidget {
  final ChatMessage message;
  final String currentUserId;

  const MessageBubble({
    Key? key,
    required this.message,
    required this.currentUserId,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final isSentByMe = message.senderId == currentUserId;

    // TODO: Build message bubble (similar to Exercise 1)
    // Use isSentByMe to determine alignment and color

    return Container(); // Replace
  }
}

// TODO: Create ChatScreen
class ChatScreen extends StatefulWidget {
  @override
  _ChatScreenState createState() => _ChatScreenState();
}

class _ChatScreenState extends State<ChatScreen> {
  // TODO: Create TextEditingController for message input

  // TODO: Create ScrollController

  // TODO: Get current user from FirebaseAuth
  // User? get currentUser => FirebaseAuth.instance.currentUser;

  @override
  void dispose() {
    // TODO: Dispose controllers
    super.dispose();
  }

  // TODO: Implement _sendMessage method
  Future<void> _sendMessage() async {
    // Get message text
    // Create message map with text, senderId, senderName, timestamp
    // Add to Firestore 'messages' collection
    // Clear text field
  }

  // TODO: Implement _logout method
  Future<void> _logout() async {
    // Sign out using FirebaseAuth
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Chat Room'),
        actions: [
          // TODO: Add logout button
          IconButton(
            icon: Icon(Icons.logout),
            onPressed: _logout,
          ),
        ],
      ),
      body: Column(
        children: [
          // TODO: Create Expanded with StreamBuilder
          // Stream: FirebaseFirestore.instance.collection('messages')
          //         .orderBy('timestamp', descending: false)
          //         .snapshots()
          // Build ListView of messages

          Expanded(
            child: Container(), // Replace with StreamBuilder
          ),

          Divider(height: 1),

          // TODO: Add message input (similar to Exercise 1)
          _buildMessageInput(),
        ],
      ),
    );
  }

  Widget _buildMessageInput() {
    // TODO: Build message input UI (same as Exercise 1)
    return Container(
      padding: EdgeInsets.all(8),
      child: Row(
        children: [
          // TODO: Add Expanded TextField

          // TODO: Add Send IconButton
        ],
      ),
    );
  }
}

/*
HINTS:

1. Firebase Initialization in main():
   WidgetsFlutterBinding.ensureInitialized();
   await Firebase.initializeApp(
     options: DefaultFirebaseOptions.currentPlatform,
   );

2. Authentication state:
   StreamBuilder<User?>(
     stream: FirebaseAuth.instance.authStateChanges(),
     builder: (context, snapshot) {
       if (snapshot.hasData) return ChatScreen();
       return LoginScreen();
     },
   )

3. Login:
   await FirebaseAuth.instance.signInWithEmailAndPassword(
     email: email,
     password: password,
   );

4. Register:
   final credential = await FirebaseAuth.instance.createUserWithEmailAndPassword(
     email: email,
     password: password,
   );
   // Create user document
   await FirebaseFirestore.instance.collection('users').doc(credential.user!.uid).set({
     'name': name,
     'email': email,
   });

5. Send message to Firestore:
   await FirebaseFirestore.instance.collection('messages').add({
     'text': text,
     'senderId': currentUser!.uid,
     'senderName': currentUser!.displayName ?? 'User',
     'timestamp': FieldValue.serverTimestamp(),
   });

6. Listen to messages:
   StreamBuilder<QuerySnapshot>(
     stream: FirebaseFirestore.instance
         .collection('messages')
         .orderBy('timestamp', descending: false)
         .snapshots(),
     builder: (context, snapshot) {
       if (!snapshot.hasData) return CircularProgressIndicator();
       final messages = snapshot.data!.docs.map((doc) =>
         ChatMessage.fromFirestore(doc)
       ).toList();
       return ListView.builder(...);
     },
   )

7. Error handling:
   try {
     await FirebaseAuth.instance.signInWithEmailAndPassword(...);
   } on FirebaseAuthException catch (e) {
     ScaffoldMessenger.of(context).showSnackBar(
       SnackBar(content: Text(e.message ?? 'Error')),
     );
   }

8. Get user name from Firestore:
   final userDoc = await FirebaseFirestore.instance
       .collection('users')
       .doc(currentUser!.uid)
       .get();
   final userName = userDoc.data()?['name'] ?? 'User';
*/
